name: S3 Access via Cognito Debug

on:
  workflow_dispatch:

jobs:
  debug-cognito:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get GitHub OIDC Token
        id: get-token
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT
          
          # Debug: Print token claims
          echo "Token claims:"
          echo $TOKEN | cut -d. -f2 | base64 -d | jq

      - name: Try Cognito GetId
        run: |
          echo "Trying Cognito GetId..."
          aws cognito-identity get-id \
            --identity-pool-id "us-east-1:5993a2a3-62da-4b8a-a25c-24a76c4b1ec4" \
            --logins "{\"token.actions.githubusercontent.com\":\"${{ steps.get-token.outputs.token }}\"}" \
            --debug

      - name: Check Cognito Identity Pool
        run: |
          echo "Checking Cognito Identity Pool configuration..."
          aws cognito-identity describe-identity-pool \
            --identity-pool-id "us-east-1:5993a2a3-62da-4b8a-a25c-24a76c4b1ec4"
