name: Test Lambda OIDC Proxy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1

      - name: Get OIDC Token and Call Lambda
        id: get-creds
        run: |
          echo "Getting OIDC token..."
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          
          echo "Calling Lambda..."
          RESPONSE=$(aws lambda invoke \
            --function-name GithubOIDCProxy \
            --payload "{\"token\":\"$TOKEN\"}" \
            --cli-binary-format raw-in-base64-out \
            response.json)
          
          echo "Lambda response status: $RESPONSE"
          cat response.json

          # Extract credentials from response
          if [ -f response.json ]; then
            CREDS=$(cat response.json | jq -r '.body' | jq -r '.')
            echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.AccessKeyId')" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.SecretAccessKey')" >> $GITHUB_ENV
            echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.SessionToken')" >> $GITHUB_ENV
          else
            echo "No response.json file found"
            exit 1
          fi

      - name: Test S3 Access
        run: |
          echo "Testing S3 access with Lambda-provided credentials..."
          echo "test content" > test.txt
          aws s3 cp test.txt "s3://test-github-oidc-bucket-20250625/${{ github.repository }}/refs/heads/${{ github.ref_name }}/test.txt"

    
