name: S3 Access via Cognito

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  s3-access:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::640168414907:role/CognitoAuthenticatedRole
          aws-region: us-east-1

      - name: Get OIDC token and Cognito credentials
        id: get_credentials
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          
          echo "Getting Cognito credentials..."
          IDENTITY_ID=$(aws cognito-identity get-id \
            --identity-pool-id "us-east-1:5993a2a3-62da-4b8a-a25c-24a76c4b1ec4" \
            --logins "{\"token.actions.githubusercontent.com\":\"$TOKEN\"}" \
            --query "IdentityId" --output text)
          
          CREDENTIALS=$(aws cognito-identity get-credentials-for-identity \
            --identity-id "$IDENTITY_ID" \
            --logins "{\"token.actions.githubusercontent.com\":\"$TOKEN\"}" \
            --query "Credentials" --output json)
          
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r .AccessKeyId)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r .SecretKey)" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r .SessionToken)" >> $GITHUB_ENV

      - name: Test S3 access
        run: |
          echo "Testing S3 access..."
          S3_PATH="${{ github.repository }}/refs/heads/${{ github.ref_name }}"
          echo "S3 Path: $S3_PATH"
          
          echo "1. Testing write access..."
          echo "test content" > test.txt
          aws s3 cp test.txt "s3://test-github-oidc-bucket-20250625/$S3_PATH/test.txt"
          
          echo "2. Testing list access..."
          aws s3 ls "s3://test-github-oidc-bucket-20250625/$S3_PATH/"
