name: Debug S3 Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: test-session

      - name: Debug Permissions
        run: |
          echo "1. Identity:"
          aws sts get-caller-identity
          
          echo "2. List IAM policies:"
          aws iam list-attached-role-policies --role-name github-oidc-role
          
          echo "3. Test basic S3 commands:"
          aws s3 ls
          aws s3 ls s3://test-github-oidc-bucket-20250625/
          
          echo "4. Try write with full path info:"
          date > test.txt
          aws s3 cp test.txt s3://test-github-oidc-bucket-20250625/test-debug.txt --debug

    
    
