name: Basic S3 Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: test-session

      - name: Test Write
        run: |
          echo "test" > test.txt
          aws s3 cp test.txt s3://test-github-oidc-bucket-20250625/test.txt

      - name: Test Read
        if: success()
        run: |
          aws s3 ls s3://test-github-oidc-bucket-20250625/

    
