name: AWS OIDC Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-oidc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.repository }}

      - name: Debug Identity
        run: |
          echo "Current identity:"
          aws sts get-caller-identity

      - name: Test S3 access
        run: |
          REPO_PATH="${{ github.repository }}"
          echo "Testing access to own repo path ($REPO_PATH)..."
          aws s3 ls s3://test-github-oidc-bucket-20250625/$REPO_PATH/ || echo "List failed"
          
          echo "Testing write to own repo path..."
          echo "test content" > test.txt
          aws s3 cp test.txt s3://test-github-oidc-bucket-20250625/$REPO_PATH/ || echo "Write failed"
          
          echo "Testing access to different path (should fail)..."
          aws s3 ls s3://test-github-oidc-bucket-20250625/different-repo/ || echo "Access denied as expected"

