name: Test S3 Access with OIDC

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: test-github-oidc-bucket-20250625

jobs:
  s3-access-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Test S3 Access
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "=== Testing from $REPO ==="
          echo ""
          
          S3_PATH="$REPO/refs/heads/$BRANCH"
          echo "S3 Path: $S3_PATH"
          
          echo "1. Testing write access..."
          echo "test content from $REPO" > test.txt
          aws s3 cp test.txt "s3://$S3_BUCKET_NAME/$S3_PATH/test.txt"
          
          echo "2. Testing read access..."
          aws s3 cp "s3://$S3_BUCKET_NAME/$S3_PATH/test.txt" ./downloaded.txt
          cat ./downloaded.txt
          
          echo "3. Testing list access..."
          aws s3 ls "s3://$S3_BUCKET_NAME/$S3_PATH/"
          
          echo "4. Testing access to different branch..."
          OTHER_BRANCH="develop"
          OTHER_PATH="$REPO/refs/heads/$OTHER_BRANCH"
          aws s3 ls "s3://$S3_BUCKET_NAME/$OTHER_PATH/" || echo "Access to different branch not allowed (expected)"
          
          echo "5. Testing access to different repository..."
          OTHER_REPO="SonarSource/different-repo"
          OTHER_PATH="$OTHER_REPO/refs/heads/$BRANCH"
          aws s3 ls "s3://$S3_BUCKET_NAME/$OTHER_PATH/" || echo "Access to different repository not allowed (expected)"

    
