name: S3 Branch-Based Access Test

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1

      - name: Test Branch-Based S3 Access
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          S3_PATH="lvtestaws123/aws-oidc-test/refs/heads/$BRANCH"
          echo "Testing access to: $S3_PATH"
          
          echo "1. Testing write to own branch..."
          echo "test content" > test.txt
          aws s3 cp test.txt "s3://test-github-oidc-bucket-20250625/$S3_PATH/"
          
          echo "2. Testing access to different branch..."
          OTHER_BRANCH=$([[ "$BRANCH" == "main" ]] && echo "develop" || echo "main")
          OTHER_PATH="lvtestaws123/aws-oidc-test/refs/heads/$OTHER_BRANCH"
          aws s3 ls "s3://test-github-oidc-bucket-20250625/$OTHER_PATH/" || echo "Access denied as expected"

    
