name: S3 Access via Lambda OIDC Proxy

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  s3-access:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role

      - name: Get GitHub OIDC Token and Call Lambda
        id: get-creds
        run: |
          echo "Getting OIDC token..."
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/lvtestaws123" | jq -r '.value')
          echo "::add-mask::$TOKEN"
          
          echo "Calling Lambda function..."
          aws lambda invoke \
            --function-name GithubOIDCProxy \
            --payload "{\"token\":\"$TOKEN\"}" \
            --cli-binary-format raw-in-base64-out \
            output.json
          
          echo "Lambda response:"
          cat output.json
          
          echo "Setting credentials..."
          CREDENTIALS=$(cat output.json | jq -r '.body' | jq -r '.')
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.SessionToken')" >> $GITHUB_ENV

      - name: Test S3 access
        run: |
          echo "Testing S3 access..."
          S3_PATH="${{ github.repository }}/refs/heads/${{ github.ref_name }}"
          echo "Testing path: $S3_PATH"
          aws s3 ls "s3://test-github-oidc-bucket-20250625/"
