name: Test S3 Access with OIDC Tags Debug

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  s3-access-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-tags: |
            repository=${{ github.repository }}
            ref=${{ github.ref }}

      - name: Debug Session
        run: |
          echo "Checking AWS identity..."
          aws sts get-caller-identity
          
          echo "Checking session tags..."
          aws sts get-caller-identity --query 'ResponseMetadata.RequestId' --output text | xargs aws cloudtrail lookup-events --lookup-attributes AttributeKey=RequestId,AttributeValue=

      - name: Test S3 Access
        run: |
          echo "Current repository: ${{ github.repository }}"
          echo "Current ref: ${{ github.ref }}"
          
          echo "Testing write access..."
          echo "test content" > test.txt
          aws s3 cp test.txt "s3://test-github-oidc-bucket-20250625/${{ github.repository }}/test.txt"

    
