name: Test S3 Access with OIDC Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: lvtestaws123-aws-oidc-test

      - name: Debug Identity
        run: |
          echo "AWS Identity:"
          aws sts get-caller-identity
          
          echo "Testing variable substitution:"
          echo "aws:userid = $(aws sts get-caller-identity --query 'UserId' --output text)"
          echo "arn = $(aws sts get-caller-identity --query 'Arn' --output text)"
          
          echo "Attempting to list bucket root:"
          aws s3 ls s3://test-github-oidc-bucket-20250625/

    
