name: S3 Branch-Based Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}

      - name: Show current identity
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          echo "Branch: ${{ github.ref_name }}"

      - name: Test S3 operations
        run: |
          echo "1. Testing upload to own branch..."
          echo "Test content from ${{ github.ref_name }} branch" > test.txt
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          
          echo "2. Testing list own branch..."
          aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"
          
          echo "3. Testing download from own branch..."
          aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" downloaded.txt
          cat downloaded.txt
          
          echo "4. Testing delete from own branch..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          
          echo "5. Testing access to other branch (should fail)..."
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          aws s3 ls "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/" || echo "Access denied as expected"
          
          echo "6. Testing upload to other branch (should fail)..."
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt" || echo "Upload to other branch failed as expected"

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up any remaining test files..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" || true
