name: AWS OIDC Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  aws-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR-AWS-ACCOUNT-ID:role/github-oidc-role
          aws-region: us-east-1
      
      - name: Test AWS access
        run: |
          aws sts get-caller-identity

    
