name: AWS OIDC Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  aws-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Test S3 Access
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          echo "Test content from ${{ github.ref_name }}" > test.txt
          
          echo "Uploading to own branch path..."
          aws s3 cp test.txt s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt
          
          echo "Listing own branch path..."
          aws s3 ls s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/
          
          echo "Attempting to list other branch (should fail)..."
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          aws s3 ls s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/ || echo "Access denied as expected"
          
          echo "Attempting to upload to other branch (should fail)..."
          aws s3 cp test.txt s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt || echo "Upload to other branch failed as expected"

    
