name: S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}

      - name: Test branch access
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          echo "Branch: ${{ github.ref_name }}"
          
          echo "1. Testing own branch access..."
          echo "Test content from ${{ github.ref_name }}" > test.txt
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          
          echo "2. Verifying content..."
          aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"
          aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" -
          
          echo "3. Cleanup..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"

    
