name: AWS S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Debug Role and Policy
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          
          echo "Current IAM policy:"
          aws iam get-role-policy --role-name github-oidc-role --policy-name S3BranchAccess

      - name: Test Basic S3 Access
        run: |
          echo "Test content" > test.txt
          
          echo "1. Testing basic upload..."
          aws s3 cp test.txt s3://github-actions-branch-test-640168414907/test.txt --debug
          
          echo "2. Testing branch-specific upload..."
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" --debug

    
