name: AWS OIDC S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Show current identity
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          aws sts get-caller-identity
          
      - name: Test S3 operations
        run: |
          # Create test file
          echo "Test content from ${{ github.ref_name }} branch at $(date)" > test.txt
          
          echo "1. Testing basic upload..."
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          
          echo "2. Listing own branch prefix..."
          aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"
          
          echo "3. Reading file content..."
          aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" -
          
          echo "4. Testing branch isolation..."
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          echo "Attempting to list other branch prefix (should fail)..."
          if aws s3 ls "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/"; then
            echo "❌ Branch isolation failed - was able to list other branch"
            exit 1
          else
            echo "✅ Branch isolation working - could not list other branch"
          fi
          
          echo "Attempting to read from other branch (should fail)..."
          if aws s3 cp "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt" test2.txt; then
            echo "❌ Branch isolation failed - was able to read from other branch"
            exit 1
          else
            echo "✅ Branch isolation working - could not read from other branch"
          fi
          
          echo "5. Cleaning up..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          
      - name: Verify cleanup
        run: |
          echo "Verifying all files were cleaned up..."
          aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"

      - name: Summary
        if: always()
        run: |
          echo "Test Summary:"
          echo "Branch: ${{ github.ref_name }}"
          echo "Role ARN: $(aws sts get-caller-identity --query 'Arn' --output text)"
          echo "-----------------------------------"
          echo "✅ Upload test passed"
          echo "✅ List operation test passed"
          echo "✅ Read operation test passed"
          echo "✅ Delete operation test passed"
          echo "❓ Branch isolation test results above"

    
