name: S3 Branch Isolation Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-isolation-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}

      - name: Verify AWS Identity
        run: |
          echo "Current identity and role session:"
          aws sts get-caller-identity
          echo "Branch: ${{ github.ref_name }}"
          
          echo "Initial bucket contents:"
          aws s3 ls s3://github-actions-branch-test-640168414907/

      - name: Test Own Branch Access
        run: |
          echo "1. Testing write access to own branch (${{ github.ref_name }})..."
          echo "Test content from ${{ github.ref_name }} branch at $(date)" > test.txt
          
          echo "Uploading to own branch prefix..."
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          
          if [ $? -eq 0 ]; then
            echo "2. Verifying content..."
            echo "Listing branch contents:"
            aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"
            
            echo "Reading uploaded file:"
            aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" -
          else
            echo "❌ Upload to own branch failed"
            exit 1
          fi

      - name: Test Cross-Branch Access
        if: always()
        run: |
          echo "3. Testing access restrictions..."
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          echo "Attempting access to $OTHER_BRANCH branch..."
          
          echo "3a. Trying to list other branch (should fail):"
          aws s3 ls "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/" && echo "❌ Can list other branch" || echo "✅ List blocked as expected"
          
          echo "3b. Trying to upload to other branch (should fail):"
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt" && echo "❌ Can write to other branch" || echo "✅ Write blocked as expected"

      - name: Cleanup
        if: always()
        run: |
          echo "4. Cleaning up..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" || echo "No file to remove"
          
          echo "Final bucket contents:"
          aws s3 ls s3://github-actions-branch-test-640168414907/ --recursive

    
