name: S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}

      - name: Debug AWS identity
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          echo "Branch: ${{ github.ref_name }}"
          
          echo "Listing S3 bucket root:"
          aws s3 ls s3://github-actions-branch-test-640168414907/

      - name: Test branch access
        run: |
          echo "1. Testing branch-specific access..."
          echo "Test content from ${{ github.ref_name }}" > test.txt
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" --debug
          
          if [ $? -eq 0 ]; then
            echo "2. Testing content retrieval..."
            aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"
            aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" - --debug
            
            echo "3. Testing cleanup..."
            aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" --debug
          fi

      - name: Test access restrictions
        if: always()
        run: |
          echo "Testing access to other branch..."
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt" || echo "✅ Access denied as expected"

    
