name: S3 Branch-Based Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}

      - name: Show current identity
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          echo "Branch: ${{ github.ref_name }}"
          
          echo "Testing basic S3 access..."
          aws s3 ls s3://github-actions-branch-test-640168414907/

      - name: Test basic upload
        run: |
          echo "Testing basic upload..."
          echo "Test content" > test.txt
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" --debug
          
          if [ $? -eq 0 ]; then
            echo "Upload successful, testing download..."
            aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" - --debug
            
            echo "Testing cleanup..."
            aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" --debug
          fi

      - name: Cleanup
        if: always()
        run: |
          echo "Final cleanup attempt..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" || true
