name: AWS OIDC Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  aws-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Test branch-based access
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          
          echo "Assumed role details:"
          aws sts get-caller-identity
          
          echo "IAM role policies:"
          aws iam list-attached-role-policies --role-name github-oidc-role
          
          echo "S3 bucket policy:"
          aws s3api get-bucket-policy --bucket github-actions-branch-test-640168414907
          
          echo "1. Testing access to own branch prefix:"
          aws s3 ls s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/
          
          echo "2. Creating and uploading test file to own branch:"
          echo "Test from ${{ github.ref_name }} branch" > test.txt
          aws s3 cp test.txt s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt --debug
          
          echo "3. Verifying file upload:"
          aws s3 ls s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/
          
          echo "4. Testing access to other branch (should fail):"
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          aws s3 ls s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/ || echo "Access denied as expected"
          
          echo "5. Testing upload to other branch (should fail):"
          aws s3 cp test.txt s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt || echo "Upload to other branch failed as expected"

    
