name: AWS OIDC S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Show current identity
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          aws sts get-caller-identity
          
      - name: Test S3 operations
        run: |
          echo "Test content from ${{ github.ref_name }} branch at $(date)" > test.txt
          
          echo "1. Testing basic upload..."
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" --debug
          
          echo "2. Listing bucket contents..."
          aws s3 ls "s3://github-actions-branch-test-640168414907/" --debug
          
          echo "3. Reading file content..."
          aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" - --debug
          
          echo "4. Deleting file..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" --debug

      - name: Check IAM permissions
        run: |
          aws iam simulate-principal-policy \
            --policy-source-arn arn:aws:iam::640168414907:role/github-oidc-role \
            --action-names s3:PutObject s3:GetObject s3:DeleteObject s3:ListBucket \
            --resource-arns arn:aws:s3:::github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt

    
