name: S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}

      - name: Debug AWS identity
        run: |
          echo "Identity and role information:"
          aws sts get-caller-identity
          echo "RoleSessionName: ${{ github.ref_name }}"
          
          echo "Testing S3 access..."
          aws s3 ls s3://github-actions-branch-test-640168414907/

      - name: Test branch access
        run: |
          echo "1. Testing upload to branch prefix..."
          mkdir -p test
          echo "Test content from ${{ github.ref_name }}" > test/test.txt
          
          # Test branch-specific access
          BRANCH_PATH="${{ github.ref_name }}"
          echo "Using branch path: $BRANCH_PATH"
          aws s3 cp test/test.txt "s3://github-actions-branch-test-640168414907/$BRANCH_PATH/test.txt" \
            --debug \
            || echo "❌ Upload failed"
          
          if [ $? -eq 0 ]; then
            echo "2. Testing list..."
            aws s3 ls "s3://github-actions-branch-test-640168414907/$BRANCH_PATH/"
            
            echo "3. Testing download..."
            aws s3 cp "s3://github-actions-branch-test-640168414907/$BRANCH_PATH/test.txt" -
            
            echo "4. Testing cleanup..."
            aws s3 rm "s3://github-actions-branch-test-640168414907/$BRANCH_PATH/test.txt"
          fi

      - name: Test access restrictions
        if: always()
        run: |
          echo "Testing cross-branch access..."
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          
          echo "Attempting to access $OTHER_BRANCH (should fail):"
          aws s3 ls "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/" \
            && echo "❌ List succeeded unexpectedly" \
            || echo "✅ List blocked as expected"
          
          aws s3 cp test/test.txt "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt" \
            && echo "❌ Upload succeeded unexpectedly" \
            || echo "✅ Upload blocked as expected"

    
