name: AWS OIDC Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  aws-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Debug Info
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          echo "Current branch: ${{ github.ref_name }}"
          echo "Testing S3 bucket access:"
          aws s3 ls s3://github-actions-branch-test-640168414907/
      
      - name: Test S3 Access
        run: |
          echo "Test content from ${{ github.ref_name }}" > test.txt
          
          echo "1. Testing bucket listing..."
          aws s3 ls s3://github-actions-branch-test-640168414907/
          
          echo "2. Uploading to own branch path..."
          aws s3 cp test.txt s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt --debug
          
          echo "3. Listing own branch path..."
          aws s3 ls s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/

    
