name: AWS S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Test S3 operations
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          
          echo "Test content from ${{ github.ref_name }}" > test.txt
          
          echo "1. Testing own branch operations..."
          # Upload
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          # List
          aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"
          # Read
          aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" -
          
          echo "2. Testing branch isolation..."
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          # Try to list other branch (should fail)
          if aws s3 ls "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/"; then
            echo "❌ Branch isolation failed - could list other branch"
            exit 1
          else
            echo "✅ Branch isolation working - could not list other branch"
          fi
          
          # Try to read from other branch (should fail)
          if aws s3 cp "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt" other.txt 2>/dev/null; then
            echo "❌ Branch isolation failed - could read from other branch"
            exit 1
          else
            echo "✅ Branch isolation working - could not read from other branch"
          fi
          
          echo "3. Cleaning up..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"

      - name: Verify cleanup
        run: |
          aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"

    
