name: AWS S3 Branch Access Test
on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-branch-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640168414907:role/github-oidc-role
          aws-region: us-east-1
          role-session-name: ${{ github.ref_name }}
      
      - name: Test Branch Isolation
        run: |
          echo "Current identity:"
          aws sts get-caller-identity
          
          echo "Creating test file..."
          echo "Test content from ${{ github.ref_name }}" > test.txt
          
          echo "1. Testing own branch operations..."
          # Upload to own branch
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"
          # List own branch
          aws s3 ls "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/"
          # Download from own branch
          aws s3 cp "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt" downloaded.txt
          
          echo "2. Testing access restrictions..."
          # Try root level upload (should fail)
          echo "Testing root upload (should fail):"
          aws s3 cp test.txt s3://github-actions-branch-test-640168414907/root_test.txt || echo "Root upload failed as expected"
          
          # Try other branch access
          OTHER_BRANCH=$([[ "${{ github.ref_name }}" == "main" ]] && echo "develop" || echo "main")
          echo "Testing other branch access (should fail):"
          aws s3 ls "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/" || echo "Other branch list failed as expected"
          aws s3 cp test.txt "s3://github-actions-branch-test-640168414907/$OTHER_BRANCH/test.txt" || echo "Other branch upload failed as expected"
          
          echo "3. Cleanup..."
          aws s3 rm "s3://github-actions-branch-test-640168414907/${{ github.ref_name }}/test.txt"

    
